### PR TITLE
Rewrite entire thing with JavaScript

### PR DESCRIPTION
**Pull request by RauliL**
Using Django which constantly shells out to execute external Python
script seems a bit heavyweight solution for such simple project, so
rewrite the entire thing with JavaScript instead.

### CODE REVIEW

**Comment by JoaRiski** [comment]
Neat, makes sense to scrap Django from here indeed 👍 

How do you run this? `package.json` seems to be referring to nonexistent `index.js` and has no custom run script. Also is the port configurable?

**Comment by RauliL** [comment]
Just run `npm start`. The portion mentioning `index.js` can be safely removed from `package.json`. Port can be configured with environment variable `PORT`.

**Comment by JoaRiski** [comment]
Ah, neat 👍 Just wondering but how does npm know what file to run? I think I've only seen projects where it's been strictly configured in the package.json before

**Comment by RauliL** [comment]
[By default `npm start` runs `server.js`.](https://docs.npmjs.com/cli/start)

**Comment by JoaRiski** [comment]
I got the node server working, but playing sound seems to not be working. Is this Windows compatible?

Also I think caching the files was good since that oddcast API rate limits when it's spammed too much, but at least cached sounds are playable then. Maybe we should just figure out how to host the TTS ourselves sometime.

**Comment by JoaRiski** [comment]
Looks like most of the supported players aren't Windows compatible and the ones that are I don't want to install, so I suppose I'll see if it just works on the actual "production" environment, heh.

**Comment by JoaRiski** [comment]
This didn't seem to work even on the linux based machine the old version was running on (for playing audio) as discussed in Slack.

Great change, but will need to get the audio working before I can merge this.

**Comment by RauliL** [comment]
This just in: Implemented the playback without use of external commands, added caching of audio files into local file system and implemented simple playback queue.

**Comment by JoaRiski** [comment]
Awesome 👍 Got this working even on windows as well now, so this is good to be merged.

Great contribution!

**Pull request merged**
